import './landingPage.scss'
import '../../components/header/header'
import '../../components/dropdown/dropdown'
import '../../components/dateDropdown/dateDropdown'
import '../../components/imageSlider/imageSlider'
