import './roomDetails.scss'
import '../../components/header/header'
import '../../components/chart/chart'
import '../../components/likeButton/likeButton'
import '../../components/bookingForm/bookingForm'
