import './cards.scss'
import '../../components/roomSearch/roomSearch'
import '../../components/registrationForm/registrationForm'
import '../../components/bookingForm/bookingForm'
import '../../components/imageSlider/imageSlider'
